plugins {
    id 'io.freefair.lombok' version '9.5.0'
    // plugin version set in settings.gradle
    id 'uk.gov.laa.springboot.laa-spring-boot-gradle-plugin'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

bootRun {
    systemProperty "spring.profiles.active", "local"
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('**/application*.yml') {
        filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [
            version: project.version.toString()
        ], beginToken: '@', endToken: '@')
    }
}

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsReportingServiceApplication.class'])
        }))
    }
}

jacocoTestCoverageVerification {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsReportingServiceApplication.class'])
        }))
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // Resolve snyk scan
    implementation(platform("io.netty:netty-codec-compression:4.2.14.Final"))
    implementation(platform("io.netty:netty-codec-http2:4.2.14.Final"))
    implementation(platform("io.netty:netty-codec-http:4.2.14.Final"))
    implementation(platform("io.netty:netty-transport-classes-epoll:4.2.14.Final"))
    implementation(platform("io.netty:netty-codec-http:4.2.14.Final"))

    // Resolve snyk scan
    implementation 'org.apache.tomcat.embed:tomcat-embed-core:11.0.22'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    implementation(platform 'software.amazon.awssdk:bom:2.45.1')
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:sts'

    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'io.prometheus:prometheus-metrics-exporter-pushgateway'

    // Required for tracing information
    implementation 'org.springframework.boot:spring-boot-micrometer-tracing-brave'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'

    implementation 'tools.jackson.dataformat:jackson-dataformat-csv:3.1.4'

    runtimeOnly 'org.springframework.boot:spring-boot-starter-flyway'
    runtimeOnly 'org.postgresql:postgresql:42.7.11'
    runtimeOnly "org.flywaydb:flyway-database-postgresql"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation "org.springframework.boot:spring-boot-starter-flyway-test"
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation "org.testcontainers:testcontainers-localstack"

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}
