plugins {
    id 'io.freefair.lombok' version '9.5.0'
    // plugin version set in settings.gradle
    id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin'
    id 'com.github.spotbugs' version '6.5.10'
}

checkstyle {
    toolVersion = '11.0.0' // Overriding until Common Plugin catches up
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

bootRun {
    systemProperty "spring.profiles.active", "local"
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('**/application*.yml') {
        filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [
            version: project.version.toString()
        ], beginToken: '@', endToken: '@')
    }
}

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsReportingServiceApplication.class'])
        }))
    }
}

jacocoTestCoverageVerification {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsReportingServiceApplication.class'])
        }))
    }
}

spotbugs {
    ignoreFailures = true
    effort = 'max'
    reportLevel = 'low'
    excludeFilter = file('spotbugs-exclude.xml')
}

spotbugsMain {
    reports {
        sarif.required = true
        html.required = true
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'

    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    implementation(platform 'software.amazon.awssdk:bom:2.51.3')
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:sts'

    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'io.prometheus:prometheus-metrics-exporter-pushgateway'

    // Required for tracing information
    implementation 'org.springframework.boot:spring-boot-micrometer-tracing-brave'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'

    // Snyk vulns
    implementation 'ch.qos.logback:logback-core:1.6.1'
    implementation 'ch.qos.logback:logback-classic:1.6.1' // override until fix available
    implementation 'org.apache.tomcat.embed:tomcat-embed-core:11.0.24'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.22'
    // The 3.x Jacksons MUST be kept in sync or they will break the build.
    implementation 'tools.jackson.core:jackson-databind:3.2.1'
    implementation 'tools.jackson.core:jackson-core:3.2.1'
    implementation 'tools.jackson.dataformat:jackson-dataformat-csv:3.2.1' // Until Spring Boot gets to 3.1.5
    // Need until AWS SDK reaches 4.2.16.Final or higher
    implementation 'io.netty:netty-codec:4.2.17.Final'
    implementation 'io.netty:netty-codec-compression:4.2.17.Final'
    implementation 'io.netty:netty-codec-http:4.2.17.Final'
    implementation 'io.netty:netty-codec-http2:4.2.17.Final'
    implementation 'io.netty:netty-handler:4.2.17.Final'
    // Need until AWS SDK reaches 5.4.3 or higher
    implementation 'org.apache.httpcomponents.core5:httpcore5-h2:5.4.3'

    runtimeOnly 'org.springframework.boot:spring-boot-starter-flyway'
    runtimeOnly 'org.postgresql:postgresql:42.7.13' // override until LAA plugin updated
    runtimeOnly "org.flywaydb:flyway-database-postgresql:13.2.0" // Override until Spring updates

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation "org.springframework.boot:spring-boot-starter-flyway-test"
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation "org.testcontainers:testcontainers-localstack"

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.14.0'
}
