spring:
  application:
    name: LAA Claims Data Reporting Application
  # Default connection details for local dev, overridden in other envs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/laa_claims_reporting_service_dev
    username: user
    password: dev
  flyway:
    schemas: claims
    create-schemas: true
    enabled: true
    locations: classpath:db/migration/schema,classpath:db/migration/replication
    placeholders:
      reporting_username: "reporting_user"
      reporting_password: "reporting_password"
      replication_source_db_url: "replication_source_db_url"
      replication_source_db_name: "replication_source_db_name"

logging:
  level:
    org.flywaydb: WARN
    org.flywaydb.core.internal.sqlscript: ERROR
    org.flywaydb.core.internal.command.DbMigrate: ERROR

# used by actuator info endpoint
info:
  app:
    name: LAA Spring Boot Microservice application
    description: An example Spring Boot Microservice application that provides a REST API.
    version: 1.0.0

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health

  # show detailed health status
  endpoint:
    health:
      show-details: always

csv-creation:
  buffer-flush-freq: 5000
  data-chunk-size: 1000
