apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-claims-reporting.fullname" . }}-metrics
  labels:
    app: {{ include "data-claims-reporting.name" . }}
spec:
  selector:
    app: {{ include "data-claims-reporting.name" . }}
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080