apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "data-claims-reporting.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 5 * * *" # Runs at 5am every day
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
          # This gives the pod aws permissions and access to envs like AWS_REGION
          serviceAccountName: {{ .Values.serviceAccount.name }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              command: ["java", "-jar", "/opt/laa-data-reporting-service/claims-reporting/app.jar"]
              env:
                - name: S3_REPORT_STORE
                  value: {{ .Values.s3.bucketName | quote }}
                - name: GATEWAY_ADDRESS
                  value: {{ .Values.pushgatewayAddress }}
                - name: JAVA_TOOL_OPTIONS
                  value: -Djava.io.tmpdir=/tmp
                - name: SPRING_PROFILES_ACTIVE
                  value: {{ .Values.service.profile | quote }}
                # Intellij complains about the below line being an invalid element, but it's fine with helm so ignore that
                {{ include "data-claims-reporting.dbConnectionDetails" . | nindent 16 }}
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
              resources:
                {{ toYaml .Values.resources | nindent 16 }}
              securityContext:
                runAsUser: 1001
                runAsGroup: 1001
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                seccompProfile:
                  type: RuntimeDefault
          volumes:
            - name: tmp
              emptyDir: {}
          restartPolicy: OnFailure