{{- if or (and (contains "uat" .Release.Namespace) (eq .Release.Name "main")) (contains "staging" .Release.Namespace) (contains "prod" .Release.Namespace)}}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: prometheus-operator
    role: alert-rules
    release: prometheus-operator
  name: prometheus-custom-rules-laa-data-claims-reporting-service-api
spec:
  groups:
    - name: kubernetes-rules
      rules:
        - alert: KubeQuota-Exceeded
          annotations:
            message: Namespace quota has exceeded the limits.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaexceeded
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: kube_resourcequota{job="kube-state-metrics",namespace="{{ .Release.Namespace }}",type="used"} / ignoring (instance, job, type) (kube_resourcequota{job="kube-state-metrics",namespace="{{ .Release.Namespace }}",type="hard"} > 0) > 0.9
          for: 15s
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: KubePodCrashLooping
          annotations:
            message: Pod has been restarting above limits for 1 hour.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace="{{ .Release.Namespace }}"}[15m]) * 60 * 5 > 0
          for: 1h
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: KubePodNotReady
          annotations:
            message: Pod has been in a non-ready state for more than 1 hour.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: sum by (namespace, pod) (kube_pod_status_phase{job="kube-state-metrics",namespace="{{ .Release.Namespace }}",phase=~"Pending|Unknown"}) > 0
          for: 1h
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: KubeDeploymentGenerationMismatch
          annotations:
            message: Deployment generation mismatch due to possible roll-back.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: (kube_deployment_status_observed_generation{job="kube-state-metrics",namespace="{{ .Release.Namespace }}"} != kube_deployment_metadata_generation{job="kube-state-metrics",namespace="{{ .Release.Namespace }}"})
          for: 15m
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: KubeDeploymentReplicasMismatch
          annotations:
            message: Deployment has not matched the expected number of replicas.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md#alert-name-kubedeploymentreplicasmismatch
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: (kube_deployment_spec_replicas{job="kube-state-metrics",namespace="{{ .Release.Namespace }}"} != kube_deployment_status_replicas_available{job="kube-state-metrics",namespace="{{ .Release.Namespace }}"})
          for: 15m
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: "Kubernetes Container OOM Killer"
          annotations:
            message: The Prometheus server uses a lot of memory and has ocassionally OOMKilled bringing down prometheus. Bump the node group monitoring instance size
            runbook_url: https://github.com/ministryofjustice/cloud-platform-infrastructure/commit/3dc05e588c9115c7aa44c2a9b5e26feff985f965
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: sum_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled", namespace="{{ .Release.Namespace }}"}[5m]) > 0
          for: 0m
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: KubeJobFailed
          annotations:
            message: Job has failed to run
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md#alert-name-kubejobfailed
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: |-
            max by (job_name, namespace) (max_over_time(kube_job_status_failed{namespace="{{ .Release.Namespace }}"}[2h]))
            * on (job_name, namespace) (time() - kube_job_created < 24 * 3600) > 0
          for: 1m
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: KubeJobNotCreated
          annotations:
            message: Job has failed to be created
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: |-
            (count(kube_job_created{namespace="{{ .Release.Namespace }}"} and (time() - kube_job_created < 24 * 3600)) or vector(0)) == 0
          # "or vector(0)" is basically saying there is a min 0. so this returns either the amount of jobs created or 0,
          # it can't return Null, which is what it would default to if no jobs are created.
          for: 1m
          labels:
            severity: {{ .Values.alerting.severity }}
    - name: application-rules
      rules:
        - alert: reportFailed
          annotations:
            message: Report {{ "{{" }} $labels.exported_job {{ "}}" }} failed to generate
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: |-
            report_success{namespace="{{ .Release.Namespace }}"} < 0
          for: 1s
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: DataRefreshTime
          annotations:
            message: Data refresh for report {{ "{{" }} $labels.exported_job {{ "}}" }} has taken more than 10 minutes
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: last_over_time(report_data_refresh_duration_ms{namespace="{{ .Release.Namespace }}"}[10m]) > 600000
          for: 1s
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: ReportGenerationTime
          annotations:
            message: Report generation for report {{ "{{" }} $labels.exported_job {{ "}}" }} has taken more than 12 minutes
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: last_over_time(report_generation_duration_ms{namespace="{{ .Release.Namespace }}"}[5m]) > 720000
          for: 1s
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: S3UploadTime
          annotations:
            message: S3 upload for report {{ "{{" }} $labels.exported_job {{ "}}" }} has taken more than 5 minutes
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: last_over_time(report_upload_time_ms{namespace="{{ .Release.Namespace }}"}[5m]) > 300000
          for: 1s
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: Utf8EncodingTime
          annotations:
            message: UTF-8 encoding verification for {{ "{{" }} $labels.exported_job {{ "}}" }} has taken more than a minute
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: last_over_time(report_encoding_check_time_ms{namespace="{{ .Release.Namespace }}"}[5m]) > 60000
          for: 1s
          labels:
            severity: {{ .Values.alerting.severity }}
        - alert: ReplicationHealthCheckFailed
          annotations:
            message: Replication health check failed
            dashboard_url: {{ .Values.alerting.grafanaDashboard }}
          expr: replication_health_check_status{namespace="{{ .Release.Namespace }}"} == 0
          for: 1m
          labels:
            severity: {{ .Values.alerting.severity }}
{{- end }}