{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "data-claims-reporting.name" . }}
  labels:
    release: {{ .Values.serviceMonitor.release | default "prometheus" }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
#      relabelings:
#        - sourceLabels: [ __meta_kubernetes_pod_label_app_kubernetes_io_name ]
#          targetLabel: container
#          action: replace
  {{- end }}
