{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "data-claims-reporting.name" . }}
  labels:
    release: {{ .Values.serviceMonitor.release | default "prometheus" }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
  {{- end }}
